### ISSUE TITLE
CUDA related error message while training neural engine with sample data

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#284]
Hello

I am using rather old GPU GeForce GT 640, but it is CUDA compatible.
Nvidia drivers are installed as per https://github.com/ModernMT/MMT/blob/master/INSTALL.md#pre-installation-actions
I am using Docker option.

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) Corpora cleaning...                                     DONE (in 2s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 7) Aligner training...                                     DONE (in 8s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 3s)
INFO: (6 of 7) Preparing training data...                              DONE (in 1m 5s)
INFO: (7 of 7) Neural decoder training...                             THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=4 : unspecified launch failure
ERROR Unexpected exception:
	RuntimeError('cuda runtime error (4) : unspecified launch failure at /pytorch/torch/lib/THC/generic/THCStorage.cu:66',)

Thanks
Mindaugas

**Comment by mindaugasDEV** [comment]
UPDATE

I get an error message also when I train phrase based engine  from the same sample data.
I am using rather minimal-spec system (for a pilot project only):
Ubuntu 16.10 64bit
Intel® Core™2 Quad CPU Q8200 @ 2.33GHz × 4  
RAM: 3,9 GiB
GeForce GT 640/PCIe/SSE2
SDD: 113,8 GB

=========== TRAINING STARTED ===========

ENGINE:  STA1
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 2s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 6) Aligner training...                                     DONE (in 8s)
INFO: (5 of 6) Translation Model training...                          ERROR Unexpected exception:
	Command '/home/mmt/mmt/build/bin/sapt_build --lex /home/mmt/mmt/runtime/STA1/tmp/training/tm/model.tlex --input /home/mmt/mmt/runtime/STA1/tmp/training/tm/corpora --model /home/mmt/mmt/engines/STA1/models/decoder/sapt -s en -t it -v /home/mmt/mmt/engines/STA1/models/decoder/vocab.vb' failed with exit code -4

Thanks,
Mindaugas

**Comment by AndRossi** [comment]
Hello @mindaugasDEV,

Could you please send me the file in path: `/home/mmtuser/mmt/runtime/STA1/logs/training.log.` of your docker image?
It is a log file that should contain more details on what went wrong with that engine.

Thank you for your patience!
Andrea

PS: this is not related to the issue you encountered, but I fear that a GT 640, having only 2GB of RAM, will not be able to train large neural models. 
In training phase, a neural MMT engine usually requires from 2 to 4 GB (sometimes even more, mostly depending on the vocabulary).
However, as I said, this does not seem to be the cause to your issue, so once we solve it you should definitely be able to train phrase-based engines and small neural engines.

**Comment by mindaugasDEV** [comment]
Hello, @AndRossi

Here it is, training.log of phrase based engine STA1.

Thanks,
Mindaugas


2017-10-14 21:34:03,993 [INFO] - Training started: engine=STA1, bilingual=3, monolingual=0, langpair=en-it
2017-10-14 21:34:03,993 [INFO] - Training step "clean_tms" (1/9) started
2017-10-14 21:34:03,995 [DEBUG] - Shell exec: java -Xmx3554m -cp /home/mmt/mmt/build/mmt-2.0.jar -Dmmt.home=/home/mmt/mmt -Djava.library.path=/home/mmt/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t it --filters normalize punctuation odd_sentences drafts sentence_length --output /home/mmt/mmt/runtime/STA1/tmp/training/clean_corpora --input /home/mmt/mmt/examples/data/train
2017-10-14 21:34:04,764 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-10-14 21:34:06,430 [INFO] - Training step "clean_tms" completed in 2 s
2017-10-14 21:34:06,430 [INFO] - Training step "create_db" (2/9) started
2017-10-14 21:34:06,432 [INFO] - Training step "create_db" completed in 0 s
2017-10-14 21:34:06,435 [INFO] - Training step "preprocess" (3/9) started
2017-10-14 21:34:06,435 [DEBUG] - Shell exec: java -cp /home/mmt/mmt/build/mmt-2.0.jar -Dmmt.home=/home/mmt/mmt -Djava.library.path=/home/mmt/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it --output /home/mmt/mmt/runtime/STA1/tmp/training/preprocessed_corpora -v /home/mmt/mmt/engines/STA1/models/decoder/vocab.vb --input /home/mmt/mmt/runtime/STA1/tmp/training/training_corpora --dev /home/mmt/mmt/engines/STA1/data/dev --test /home/mmt/mmt/engines/STA1/data/test
2017-10-14 21:34:07,053 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-10-14 21:34:08,818 [INFO] - Training step "preprocess" completed in 2 s
2017-10-14 21:34:08,819 [INFO] - Training step "train_context" (4/9) started
2017-10-14 21:34:08,819 [DEBUG] - Shell exec: java -cp /home/mmt/mmt/build/mmt-2.0.jar -Dmmt.home=/home/mmt/mmt -Djava.library.path=/home/mmt/mmt/build/lib eu.modernmt.cli.ContextAnalyzerMain -s en -t it -i /home/mmt/mmt/engines/STA1/models/context -c /home/mmt/mmt/runtime/STA1/tmp/training/training_corpora
2017-10-14 21:34:09,429 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-10-14 21:34:09,878 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 1
2017-10-14 21:34:09,911 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 2
2017-10-14 21:34:09,947 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 3
2017-10-14 21:34:09,947 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Flushing index to disk. Pending updates: 3
2017-10-14 21:34:09,950 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket CorpusBucket{memory=3, direction=en → it}
2017-10-14 21:34:09,950 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket CorpusBucket{memory=1, direction=en → it}
2017-10-14 21:34:09,951 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-3] Indexing bucket CorpusBucket{memory=2, direction=en → it}
2017-10-14 21:34:10,574 [INFO] - Training step "train_context" completed in 1 s
2017-10-14 21:34:10,575 [INFO] - Training step "train_aligner" (5/9) started
2017-10-14 21:34:10,579 [DEBUG] - Shell exec: /home/mmt/mmt/build/bin/fa_build -s /home/mmt/mmt/runtime/STA1/tmp/training/aligner/merge.en -t /home/mmt/mmt/runtime/STA1/tmp/training/aligner/merge.it -m /home/mmt/mmt/engines/STA1/models/aligner/en__it.mdl -I 4
Creating vocabulary... DONE in 0.128122s
== Forward model training ==
Initial setup... DONE in 0.558555s
Iteration 1:
	Computing alignments... DONE in 0.459998s
	Optimizing diagonal tension... DONE in 0.127s
	Normalizing translation table... DONE in 0.22066s
Iteration 2:
	Computing alignments... DONE in 0.454877s
	Optimizing diagonal tension... DONE in 0.127661s
	Normalizing translation table... DONE in 0.222582s
Iteration 3:
	Computing alignments... DONE in 0.455405s
	Optimizing diagonal tension... DONE in 0.125092s
	Normalizing translation table... DONE in 0.222221s
Iteration 4:
	Computing alignments... DONE in 0.455284s
	Optimizing diagonal tension... DONE in 0.125279s
	Normalizing translation table... DONE in 0.222766s
Pruning model... DONE in 0.190439s

Training done in 3.96975s

== Backward model training ==
Initial setup... DONE in 0.523937s
Iteration 1:
	Computing alignments... DONE in 0.471597s
	Optimizing diagonal tension... DONE in 0.129746s
	Normalizing translation table... DONE in 0.230652s
Iteration 2:
	Computing alignments... DONE in 0.467938s
	Optimizing diagonal tension... DONE in 0.127325s
	Normalizing translation table... DONE in 0.232031s
Iteration 3:
	Computing alignments... DONE in 0.470157s
	Optimizing diagonal tension... DONE in 0.127335s
	Normalizing translation table... DONE in 0.233565s
Iteration 4:
	Computing alignments... DONE in 0.469976s
	Optimizing diagonal tension... DONE in 0.127381s
	Normalizing translation table... DONE in 0.233889s
Pruning model... DONE in 0.128749s

Training done in 3.97612s

Writing model...DONE in 0.133664s
2017-10-14 21:34:18,820 [INFO] - Training step "train_aligner" completed in 8 s
2017-10-14 21:34:18,820 [INFO] - Training step "write_config" (6/9) started
2017-10-14 21:34:18,821 [INFO] - Training step "write_config" completed in 0 s
2017-10-14 21:34:18,825 [INFO] - Training step "train_tm" (7/9) started
2017-10-14 21:34:18,827 [DEBUG] - Shell exec: /home/mmt/mmt/build/bin/fa_align --model /home/mmt/mmt/engines/STA1/models/aligner/en__it.mdl --input /home/mmt/mmt/runtime/STA1/tmp/training/tm/corpora --output /home/mmt/mmt/runtime/STA1/tmp/training/tm/corpora --source en --target it --strategy 1
2017-10-14 21:34:19,864 [DEBUG] - Shell exec: /home/mmt/mmt/build/bin/fa_export --model /home/mmt/mmt/engines/STA1/models/aligner/en__it.mdl --output /home/mmt/mmt/runtime/STA1/tmp/training/tm/model.tlex
2017-10-14 21:34:20,325 [DEBUG] - Shell exec: /home/mmt/mmt/build/bin/sapt_build --lex /home/mmt/mmt/runtime/STA1/tmp/training/tm/model.tlex --input /home/mmt/mmt/runtime/STA1/tmp/training/tm/corpora --model /home/mmt/mmt/engines/STA1/models/decoder/sapt -s en -t it -v /home/mmt/mmt/engines/STA1/models/decoder/vocab.vb
2017-10-14 21:34:20,552 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/mmt/mmt/cli/mmt/engine.py", line 475, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/mmt/mmt/cli/mmt/engine.py", line 290, in __call__
    self._f(*args, **kwargs)
  File "/home/mmt/mmt/cli/mmt/phrasebased.py", line 322, in _train_tm
    self._engine.moses.pt.train(corpora, self._engine.aligner, working_dir, log=log)
  File "/home/mmt/mmt/cli/mmt/phrasebased.py", line 183, in train
    shell.execute(command, stdout=log, stderr=log)
  File "/home/mmt/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/mmt/mmt/build/bin/sapt_build --lex /home/mmt/mmt/runtime/STA1/tmp/training/tm/model.tlex --input /home/mmt/mmt/runtime/STA1/tmp/training/tm/corpora --model /home/mmt/mmt/engines/STA1/models/decoder/sapt -s en -t it -v /home/mmt/mmt/engines/STA1/models/decoder/vocab.vb' failed with exit code -4

**Comment by mindaugasDEV** [comment]
Hi again @AndRossi 

Thanks for the remark about slow GPU. I planned to play with pilot project and then buy GeForce GTX1080i and use a more powerful server installation. However, first I need to test how MMT handles XML tags and SDLXLIFF file format.

Update about Neural Engine error messages:
Good news, CUDA related messages are gone (maybe restarting helped), I also know that I shall ignore Deprecation messages, now waiting for NeuralEngine to be created.  

mmt@0c7d4b60af3d:~/mmt$ ./mmt create en it examples/data/train --neural

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 7) Corpora cleaning...                                     DONE (in 2s)
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 7) Aligner training...                                     DONE (in 8s)
INFO: (5 of 7) Creating translation memory...                          DONE (in 3s)
INFO: (6 of 7) Preparing training data...                              DONE (in 60s)
INFO: (7 of 7) Neural decoder training...                             /home/mmt/mmt/build/lib/pynmt/nmmt/NMTEngineTrainer.py:177: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()
/home/mmt/mmt/build/lib/pynmt/nmmt/NMTEngineTrainer.py:177: UserWarning: self and mask not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()


Thanks, Mindaugas

**Comment by AndRossi** [comment]
Hi @mindaugasDEV,

Those are great news!
When the neural training is over please let me know if it was successful.
Also, could you please try again to train your phrase-based engine and see whether its problem is gone as well? Thank you!

By the way, I can confirm you that GTX1080Ti is an excellent choice.
It is one of the GPUs that we used in development and test, and it is probably the best one in terms of cost/performance :) 

Andrea

**Comment by mindaugasDEV** [comment]
Hi, @AndRossi 

Q1: Neural engine is still being trained. It is being run for 12 hours with sample data from MMT repository (3 corpuses, each 2000 lines: IBM, Microsoft, Europarl). Is it normal for a slow PS like mine (GPU 2 Gb of RAM, Core2 CPU, 4 Gb OS RAM)? Or shall I interrupt it? (GPU fan became loud at the training start and still makes buzz, is it the only indication that work is being done? )

Q2. Where can I see the progress of Neural and Phrase engines while they are being trained? Are there any logs to look into and be calm that it has not stuck yet?  I understand that I cannot estimate the finish time, but at least indication that „it has not stuck yet, be patient and wait“ would be beneficial.

Q3. While the above error messages came from Docker, I have installed MMT binaries too along side with Docker and ran statistical engine from MMT sample data and it returned the same error as reported above. Log and TMP directory is zipped and accessible via link: https://we.tl/dgxE8vrSde 

Thanks,
Mindaugas

**Comment by mindaugasDEV** [comment]
Hi, @AndRossi 

I have installed MMT to server environment with proper CPU and RAM (no GPU, though), then downloaded MMT binaries and launched creation of PHRASE engine from MMT sample.
Still the same error=
xxxxxxxx/models/decoder/vocab.vb' failed with exit code -4

Log and TMP folders of new system attached via link: https://we.tl/S2tZHeB3kU

If it does not run on 2 different systems, and via 2 different installation methods (Docker and Binaries), there is bigger chance that origin of the problem is not in my systems. Can you check?

Thanks,
Mindaugas

**Comment by mindaugasDEV** [comment]
Hi, @AndRossi 

UPDATE: after unsuccessful try of 1) Docker option and 2) Binaries option, I have tried 3) Building binaries myself. It worked! 

Now I can train phrase based engine from MMT sample data and translate it.

I have solved my problem, but you might want to check why Docker and Binaries options did not work on 2 different computers. The other users might also report the same problem as not everybody wants to mess with [relatively] more complex Compiling method.

Shall I close the issue or you want to keep it open for investigation?

Thanks,
Mindaugas

**Comment by AndRossi** [comment]
Hi @mindaugasDEV,

I'm glad you got the software to work!
For the time being, please keep this issue open. As you said, it might be useful for other users while we investigate this issues.
I will proceed to close it when we find out what caused the docker and binaries errors and fix it.

For any doubt or further problem, don't hesitate to ask :)
Thanks again for your patience and support!

Andrea

**Comment by AndRossi** [comment]
Hi again @mindaugasDEV,
I have tested a phrase-based engine both on docker and from binaries, and on my environment (an AWS r4.large EC2 with Trusty AMI) they seemed to work fine.
Can you please provide me with more information on your environments? 
This way it should be easier to replicate the issue.

Thank you again!

Andrea

**Comment by mindaugasDEV** [comment]
Hi, again @AndRossi 

I have tested Docker and Binaries options on both systems:

1) old desktop PC with GPU:
Ubuntu 16.04.3 LTS (Xenial Xerus)
Intel® Core™2 Quad CPU Q8200 @ 2.33GHz × 4
RAM: 3,9 GiB
GeForce GT 640/PCIe/SSE2
SDD: 113,8 GB

2) virtual machine (VM) on Windows 2012 server:
in VM there are following settings:
- RAM 2024 Mb Dynamically expandable till 1040000
- HDD container: 128 Gb
- 16 Virtual CPUs 
- Ubuntu 16.04.3 LTS (Xenial Xerus)

Compiling binaries myself worked on both.
BTW, neural training in Docker on 1) system finished after 14 hours with message in command prompt „Killed“.
I took it as a critical error and started new Neural training process outside Docker, in MMT environment, compiled by myself (leaving only 1 sample corpus instead of 3 not to waste time for 12 hours).  Or did it mean that Neural training was finished successfully?


Regards,
Mindaugas

**Comment by AndRossi** [comment]
No, that neural training was probably not successful.
I'll let you know as soon as I find out what is causing this issue :) 

Best,
Andrea

**Comment by mindaugasDEV** [comment]
I have launched Neural engine in Docker and it launched fine, now it is „Loading models“. So far no error was produced, but it stuck on that message.

I have sent you only logs for Phrase based engine (STA1) (in Docker or outside). I will extract Neural engine logs after Loading models error is gone. Probably after 12 hours.

Best,
Mindaugas

**Comment by mindaugasDEV** [comment]
I have another problem: after creating Phrase engine on Server installation (powerful, but without GPU), I have started Phrase-based engine training with 1G data (35M words), hoping to create production engine. However, it stopped when creating language models:

./mmt create en lt examples/data/train -e SMT1

=========== TRAINING STARTED ===========

ENGINE:  SMT1
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 1 documents
LANGS:   en > lt

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 7m 12s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 2m 16s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 1m 7s)
INFO: (4 of 6) Aligner training...                                     DONE (in 12m 34s)
INFO: (5 of 6) Translation Model training...                           DONE (in 17m 31s)
INFO: (6 of 6) Language Model training...                             ERROR Unexpected exception:
	Command '/home/usermk/ModernMT/build/bin/vb_encode -v /home/usermk/ModernMT/engines/SMT1/models/decoder/vocab.vb -i /home/usermk/ModernMT/runtime/SMT1/tmp/training/lm/slm.temp/corpora | /home/usermk/ModernMT/build/bin/create_slm --discount-fallback -o 5 -a 32 -q 8 --type trie --model /home/usermk/ModernMT/engines/SMT1/models/decoder/lm/background.slm -T /home/usermk/ModernMT/runtime/SMT1/tmp/training/lm/slm.temp --prune 0 1 2' failed with exit code -6

The log attached. I used 1 monolingual file and 2 normal TMX files + 1 dictionary, converted to TMX file.
[training.log](https://github.com/ModernMT/MMT/files/1385571/training.log)

Thanks,
Mindaugas

**Comment by mindaugasDEV** [comment]
please ignore the last message about 1 Gb SMT engine. It was data encoding problem, files were prepared in Windows, therefore I needed to change end of line symbols to Unix LF and it went through fine.

Mindaugas

**Comment by AndRossi** [comment]
Hello @mindaugasDEV, 

We have released MMT version 2.0.1 with several bugfixes, and we encountered no problems with its new binaries in our enviromnent, so everything should be working fine now.

I am closing this issue now; for any further problem please contact us or re-open it.

Thank you again for your great support!

Andrea
