### ISSUE TITLE
failure of mmt create --neural in docker image (missing nvidia libs)

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#358]
The command
`./mmt create en it examples/data/train --neural`
fails at the very beginning, when the command
`nvidia-smi --query-gpu=memory.total--format=csv,noheader,nounit`
is invocated.

The reason is that the low level nvidia libs /usr/local/nvidia/lib64/* are not seen by the command "mmt" -- while in the bash they are seen by means of the env variable LD_LIBRARY_PATH

As a temporary fix, I have manually added symbolic links to such libs in the MMT_HOME/build/lib dir, with the following commands:
```
cd build/lib ; for f in /usr/local/nvidia/lib64/* ; do ln -s $f . ; done

```
After that, the "mmt create ... " command worked correcltly.

By the way, with the above fix the GPU is used also at decoding time; without the above fix, the GPU is not used at decoding time.

**Comment by davidecaroselli** [comment]
Hi @cattoni 

thanks for the bug report. We have just released a new docker image with **ModernMT v3.0** and I've tested train and translation: it all seems to work now!

If you have any other issues please don't hesitate to re-open this issue.

Cheers,
Davide
